apiVersion: v1
kind: Pod
metadata:
  name: hey-nginx
  labels:
    app: hey-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.11
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/nginx/html/
  volumes:
    - name: config-volume
      configMap:
        name: my-config
        items:
        - key: index.html
          path: info.html
