apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  ports:
  - name: http
    port: 31001
    nodePort: 31001
    targetPort: http-port
    protocol: TCP
  - name: mysql
    port: 31002
    nodePort: 31002
    targetPort: mysql-port
    protocol: TCP
  selector:
    app: wordpress
  type: NodePort
